### ISSUE TITLE
IDE-Tab won't work

### ISSUE THREAD

**Issue by Petschko** [cocuh/intellij-wallpaper#3]
Hello,

first thanks for your awesome plugin :3 !

But I run in an issue (or not developed) in the settings. I guess, that the IDE-Tab is for the Background of the IDE (Fileexplorer etc) but it doesn't change anything if I set stuff up in there...

See here: http://www.fotos-hochladen.net/uploads/phpstormlookfi05m1o2t8.png - Only the Editor has the Background Image.

Thank you for your time =)

Petschko

**Comment by cocuh** [comment]
`IDE`` means the background of window, not file trees. This plugins can't set background of file trees. Thank you for issue.

![hoge](https://cloud.githubusercontent.com/assets/1741999/15960543/49b4d75a-2f3b-11e6-88ea-dc73633a872f.png)
