### ISSUE TITLE
Can't save Settings on Linux PHP-Storm

### ISSUE THREAD

**Issue by Petschko** [cocuh/intellij-wallpaper#4]
Hello,

I've installed this Plugin on Linux-Cinnamon PHP-Storm, it worked pretty good aside, that I can't save the settings if this plugin is enabled. If I disable this Plugin I CAN save the settings. But if I activate this plugin I've get a lot of those messages:
12:39:20 Unable to save settings: Failed to save settings. Please restart PhpStorm

This is the only plugin that I use, so there can't be a conflict with an other plugin. I have this plugin also on my PHPStorm on Windows and there is every thing fine.

OS: Linux Mint Cinnamon (64bit)
Program: PHPStorm 10.0.4 (Build PS#143.2370)
JRE: 1.8.0_60-b27

Sorry again for the bad english =/ And thanks for reading

**Comment by cocuh** [comment]
Update your phpstorm. This plugin use relatively latest Jetbrain IDE APIs(which implemented in March 2016).

If you cannot save config on latest phpstorm, check your permission of `~/.PhpStorm2016.1`. It seems IDE failed to create config files. The config file path is `~/.PhpStorm2016.1/config/options/wallpaper_editor_settings.xml` as default.

My English is also poor. Never mind;)

**Comment by Petschko** [comment]
Ah thanks, I see the Problem... My bad, I've used a little old version I guess its time for an Update :)
Your Plugin worked with the old version too, and I guess I know why it can't save the settings on the old version!

Config Paths of PHP-Storm:
143.2370 - ~/.WebIde100/
145.1616 - ~/.PhpStorm2016.1/

The Config-Location ~/.PhpStorm2016.1/ doesn't exist on my Computer yet. Thank you, so this is not an issue.

Thanks for the answer =)

Petschko

Edit: It worked perfectly fine with the new Version.
