### ISSUE TITLE
hi, I have some problem

### ISSUE THREAD

**Issue by fyzzy1943** [cocuh/intellij-wallpaper#5]
I reinstall my computer yesterday, and install phpstorm, then install this plugin, but it doesn't work. I don't know what the problem is, thank you.

my invironment:
PhpStorm 2016.2
Build #PS-162.1121.38, built on July 12, 2016
JRE: 1.8.0_76-release-b216 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

**Comment by cocuh** [comment]
Thank you for issue report.
Jetbrains implements background officially. https://www.jetbrains.com/help/phpstorm/2016.2/setting-background-image.html
Anyway this plugin's role is over.

**Comment by fyzzy1943** [comment]
oh! thank you~
It's the same as this plugin.
